### ISSUE TITLE
No "Set Drivers to Highlight" Option

### ISSUE THREAD

**Issue by etmidust** [Fuzzwah/iRacing-My-Results-Highlighter#2]
Using Firefox, after the update, when clicking the tampermonkey icon, no "set drivers to highlight" comes up. and after opening the results page the script doesn't even show as running. It seems to be an error at line 25.
![image](https://user-images.githubusercontent.com/64505557/80546632-6e1f2280-8973-11ea-936a-84c1c59dfdd7.png)
![image](https://user-images.githubusercontent.com/64505557/80546685-8f800e80-8973-11ea-97e2-2047f7f7759d.png)
![image](https://user-images.githubusercontent.com/64505557/80546904-1503be80-8974-11ea-9bae-a62775afb745.png)

**Comment by Fuzzwah** [comment]
Can you show me what you see when you view your tampermonkey dashboard?

It seems like tampermonkey hasn't downloaded one of the external scripts that is required:

```
// @require       https://raw.githubusercontent.com/fuzzwah/iRacing-My-Results-Highlighter/master/waitForKeyElements.js
```

**Comment by etmidust** [comment]
This is what I see.
I hope this helps. Let me know if there are other things you need to see.

![image](https://user-images.githubusercontent.com/64505557/81510725-22ed0400-92d1-11ea-9877-065cb717b2e8.png)

**Comment by Fuzzwah** [comment]
Can you confirm that you're allowing external scripts in your tampermonkey settings?

![image](https://user-images.githubusercontent.com/658935/81510810-18c21880-9358-11ea-852b-fef871b3c354.png)

**Comment by etmidust** [comment]
can confirm. I have the same two boxes checked that you do.

**Comment by Fuzzwah** [comment]
Baffling. I just installed the script successfully in firefox on a machine that didn't previously have it.

Can you hover over the green icon in the dashboard for me please. Mine looks like this:

![image](https://user-images.githubusercontent.com/658935/81510927-faa8e800-9358-11ea-9f44-abddc4dd314a.png)

**Comment by etmidust** [comment]
same... Could it maybe be something to do with AdBlock Plus or UBlock Origin?

![image](https://user-images.githubusercontent.com/64505557/81510943-0651cb80-92d3-11ea-8d65-17a4a30f0557.png)

**Comment by Fuzzwah** [comment]
I don't think adblock will block the download of the files, the machine I'm testing firefox on has UBlock Origin installed.

Can you try removing the script and installing it again fresh? I'm wondering if something went wrong while tampermonkey was doing it's auto update of the script.

**Comment by Fuzzwah** [comment]
Another thing to try is to force an update check:

![image](https://user-images.githubusercontent.com/658935/81511017-a2beb100-9359-11ea-881e-b29f452cc4d0.png)

**Comment by Fuzzwah** [comment]
Oh!

The option to configure the drivers only shows up when you're viewing a results page!

**Comment by Fuzzwah** [comment]
Can you click this link and then check if the menu is populated?

https://members.iracing.com/membersite/member/EventResult.do?&subsessionid=32324684

**Comment by etmidust** [comment]
Thats it! Wow, thank you. When I click results it opens in a new tab that doesn't have all the browser functions available... Copying the address worked

![image](https://user-images.githubusercontent.com/64505557/81511075-fbe40180-92d3-11ea-95dd-41a8b2edba5b.png)

**Comment by Fuzzwah** [comment]
Thanks for bringing this to my attention and helping me get to the bottom of it!

I've updated the readme to clearly explain what we've worked out. Have a great day.
